import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1600, height: 1000 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.goto('http://localhost:8080/auth', { waitUntil: 'networkidle' });
await page.fill('#signin-email', 'neo-qa@redwood.so');
await page.fill('#signin-password', 'neoqa-2026-Sendr!');
await page.click('button[type="submit"]');
await page.waitForURL('**/queue', { timeout: 15000 });
await page.waitForTimeout(2500);
await page.keyboard.press('Escape');
await page.click('text=Open ›');
await page.waitForTimeout(3500);
await page.screenshot({ path: '/tmp/q2-expanded.png' });
await page.mouse.wheel(0, 500);
await page.waitForTimeout(800);
await page.screenshot({ path: '/tmp/q3-slices.png' });
await page.mouse.wheel(0, 900);
await page.waitForTimeout(800);
await page.screenshot({ path: '/tmp/q4-slices2.png' });
await browser.close();
console.log('done');
